# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 479b068e7174984d4c70d2fb4ea1297e1bb918886781f6fb21258d6acbe019852f67b82a71b1343f71406762a45761e55856c105413c806ec21a5547d4d07e92

test:
  secret_key_base: 938642f43f1e8b209adbf1656ec855945c2c3f11da7bb59783079a9347433e67b1afbdde0d677e9a272090ad201b8735064f24f80793357128d9cb29745505aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
